image: gradle:alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build:
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
